### ISSUE TITLE
Archive source webpages

### ISSUE THREAD

**Issue by grill05** [grill05/misc_bed_availability_scraper#20]
For now, we just download the respective city/state dashboard pages via curl/requests, extract data, and move on

While this is fine, one drawback is that data that exists on the downloaded dashboard page (district breakup etc) that we don't extract, is automatically lost (the states/cities themselves tend to use "live" dashboards only, with no archiving feature)

So I was wondering if it made sense to save the source pages (also) in this/another repo?

For eg: Mumbai's dashboards contain a lot more data than extracted by scraper.py, but the download link https://stopcoronavirus.mcgm.gov.in/assets/docs/Dashboard.pdf is overwritten every day. So, to keep the possibility of parsing additional data (sometime in the future) open, I've been archiving the pdfs in https://github.com/grill05/mumbai_mcgm_dashboards_archive/tree/master/mumbai_dashboards

One advantage is that other folk/reasearchers could also use the archived pages themselves, without having to rely on/trust our code 

Is it worth doing this? or is it too much work for too little gain?

**Comment by saketkc** [comment]
Great idea. We also do not collect some more fine grained information - like private vs public or male vs female bed occupany (in states where it is reported) which I am personally very interested in. This is also easily doable (without necessarily creating a separate repo for each state) by just repurposing the existing code to dump a downloaded file if it's md5 hash is different from the hash of existing files.

**Comment by grill05** [comment]
added some preliminary code to do this in commit b2a9bee3ce2af58b3f39960298bdbac39668dbd0

Relevant code is in archive_raw_source(city,html_str). Only html sources (and json's in case of delhi) are archived for now

Some cities have similar "live" pdfs (link overwritten every day) such as ludhiana etc. Still thinking how to archive those (without ballooning the size of the repo)..
