### ISSUE TITLE
Rajasthan: Incorrect results

### ISSUE THREAD

**Issue by saketkc** [grill05/misc_bed_availability_scraper#21]
72k ventilator beds doesn't make sense, probably an error during parsing, though even dropping the last two digits would not make it follow any trend: artifact of using a subset of the hospitals maybe?
![newplot (1)](https://user-images.githubusercontent.com/682153/149957379-17c88ff1-5a79-442e-ba35-730897d07998.png)

**Comment by grill05** [comment]
yes, that's correct

Not sure where it was going wrong, but I changed that part of the code to read the html table (from RJ dashboard) via pandas (pd.read_html), and it seems to be working ok for now

The capacity data for prior days seems correct, but occupancy figures are messed up. So removing prior occupancy figures for now( better to not show data, than to show incorrect data,imo)

Underlines the importance of archiving source pages, to prevent data losses of this kind, among other reasons. I'll try and get started with that (for atleast states, if not cities) soon..
