### ISSUE TITLE
Ahmedabad

### ISSUE THREAD

**Issue by saketkc** [grill05/misc_bed_availability_scraper#7]
(Sorry for opening multiple issues - I think it is best you make the decision on including a city)

```python
url = "https://ahmedabadcity.gov.in/portal/COVID19.jsp"

options = webdriver.ChromeOptions()
options.add_argument("--ignore-certificate-errors")
options.add_argument("--headless")
br = webdriver.Chrome(chrome_options=options)
br.get(url)
soup = BeautifulSoup(br.page_source, "html.parser")
for body in soup("tbody"):
    body.unwrap()

dfs = pd.read_html(str(soup), flavor="bs4")
dff = dfs[0]
isolation_beds, o2_beds, icu_ventilator_beds, icu_noventilator_beds = dff.iloc[
    0
].tolist()
```

**Comment by grill05** [comment]
thanks. Looks good.

Maybe commit this (with city=='ahmedabad')
Once initial actions runs for ahmedabad work (ssh access via upterm can help if any failues+only running for ahmedabad to avoid waiting for other cities scraper to finish), I'll add the city to the tracker as well
